application:
  security:
    jwt:
      secret-key: 931429B246551C8C2BBDCFD6CA492931429B246551C8C2BBDCFD6CA492
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/engconc
    username: postgres
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 3001
VITE_BACKEND_DEV: http://localhost:3001
meta:
  env:
    VITE_BACKEND_DEV: http://localhost:3001



#Deploy Hostgator-------------
#spring.datasource.url=
#spring.datasource.username=renandesouza
#spring.datasource.password=Eumesmo1!Aws
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
